tree = input("type a kind of tree ")
insect = input("type a kind of insect ")
verb = input("wat kind of verb does ur insect do ")
print("/n/n")
print("   There was an Old Man in a " +tree)
print("Who was horribly bored by a " +insect)
print("   When they said, 'Does it " +verb+ "?' ")
print("He replied, 'Yes, it does!' ")
print("   It's a regular brute of a Bee!")
print("                         Edward Lear")